"use client"

import { useState, useEffect } from "react"
import { useRouter } from "next/navigation"
import {
  Briefcase,
  FileText,
  Download,
  CheckCircle2,
  Star,
  Eye,
  Trash2,
  ExternalLink,
  Pencil,
  RotateCcw,
} from "lucide-react"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import { Checkbox } from "@/components/ui/checkbox"
import { Progress } from "@/components/ui/progress"
import { Separator } from "@/components/ui/separator"
import { useAuth } from "@/components/providers/auth-provider"
import { toast } from "sonner"
import { STORY_TYPE_LABELS } from "@/lib/types"

// Storage key for portfolio submissions
const PORTFOLIO_STORAGE_KEY = "newsroomlab_portfolio"

// Demo pieces to show when no submissions exist
const demoPieces = [
  {
    id: "demo_1",
    title: "Sample: Nairobi Allocates Ksh 38.7B in New Budget",
    storyType: "HARD_NEWS",
    course: "HCC 314",
    date: "March 2026",
    score: 78,
    verifications: 10,
    selected: false,
    isDemo: true,
  },
]

function generatePortfolioHTML(pieces, user) {
  const selected = pieces.filter((p) => p.selected && !p.isDemo)
  return `<!DOCTYPE html>
<html><head><meta charset="utf-8"><title>Portfolio — ${user?.name || "Student"}</title>
<style>
  body { font-family: Georgia, serif; max-width: 800px; margin: 40px auto; color: #1a1a1a; line-height: 1.6; }
  h1 { font-size: 28px; border-bottom: 3px solid #1a1a1a; padding-bottom: 12px; }
  h2 { font-size: 20px; margin-top: 40px; color: #333; }
  .meta { color: #666; font-size: 14px; margin-bottom: 8px; }
  .piece { page-break-inside: avoid; margin-bottom: 40px; padding: 20px; border: 1px solid #e5e5e5; border-radius: 8px; }
  .badge { display: inline-block; background: #f0f0f0; padding: 2px 8px; border-radius: 4px; font-size: 12px; margin-right: 4px; }
  .score { float: right; font-size: 24px; font-weight: bold; color: #166534; }
  .section-label { font-weight: bold; font-size: 13px; text-transform: uppercase; letter-spacing: 1px; color: #666; margin-top: 16px; }
  .story-text { background: #fafafa; padding: 16px; border-radius: 4px; font-size: 14px; white-space: pre-wrap; }
  .footer { margin-top: 60px; text-align: center; font-size: 12px; color: #999; border-top: 1px solid #e5e5e5; padding-top: 12px; }
  @media print { body { margin: 20px; } .piece { border: none; border-bottom: 1px solid #ccc; } }
</style></head><body>
<h1>Journalism Portfolio</h1>
<p class="meta"><strong>${user?.name || "Student Name"}</strong> · ${user?.email || ""} · ${new Date().toLocaleDateString("en-GB", { month: "long", year: "numeric" })}</p>
<p class="meta">${selected.length} selected piece${selected.length !== 1 ? "s" : ""} · Generated from NewsroomLab AI</p>
<hr>
${selected.map((p, i) => `
<div class="piece">
  ${p.score ? `<div class="score">${p.score}%</div>` : ""}
  <h2>${i + 1}. ${p.title || p.headline || "Untitled Story"}</h2>
  <p class="meta">
    <span class="badge">${STORY_TYPE_LABELS[p.storyType] || p.storyType}</span>
    <span class="badge">${p.course}</span>
    ${p.date}
  </p>
  ${p.draftContent ? `
  <p class="section-label">Story</p>
  <div class="story-text">${p.draftContent}</div>
  ` : ""}
  <p class="section-label">Verification</p>
  <p>${p.verifications || 0} claims independently verified</p>
  ${p.reflectionAnswers && Object.keys(p.reflectionAnswers).length > 0 ? `
  <p class="section-label">Reflection</p>
  <p>${Object.values(p.reflectionAnswers).filter(Boolean).join(" ").slice(0, 500)}${Object.values(p.reflectionAnswers).join(" ").length > 500 ? "..." : ""}</p>
  ` : `
  <p class="section-label">Reflection</p>
  <p><em>Reflection included in submission</em></p>
  `}
</div>`).join("\n")}
<div class="footer">
  <p>This portfolio was generated by NewsroomLab AI on ${new Date().toLocaleDateString("en-GB", { day: "numeric", month: "long", year: "numeric" })}.</p>
  <p>All stories include verification tables, AI disclosure, and student reflections.</p>
</div>
</body></html>`
}

export default function PortfolioPage() {
  const { user } = useAuth()
  const [pieces, setPieces] = useState([])
  const [loading, setLoading] = useState(true)
  
  // Load submissions from localStorage on mount
  useEffect(() => {
    const loadPortfolio = () => {
      try {
        const saved = localStorage.getItem(PORTFOLIO_STORAGE_KEY)
        if (saved) {
          const submissions = JSON.parse(saved)
          // Add selected: false to any submissions that don't have it
          const normalizedSubmissions = submissions.map(s => ({
            ...s,
            selected: s.selected ?? false,
          }))
          setPieces(normalizedSubmissions.length > 0 ? normalizedSubmissions : demoPieces)
        } else {
          setPieces(demoPieces)
        }
      } catch (e) {
        console.error("Failed to load portfolio:", e)
        setPieces(demoPieces)
      }
      setLoading(false)
    }
    loadPortfolio()
  }, [])
  
  // Save selection changes to localStorage
  const updatePiecesAndSave = (newPieces) => {
    setPieces(newPieces)
    const toSave = newPieces.filter(p => !p.isDemo)
    localStorage.setItem(PORTFOLIO_STORAGE_KEY, JSON.stringify(toSave))
  }

  const togglePiece = (id) => {
    const newPieces = pieces.map((p) => (p.id === id ? { ...p, selected: !p.selected } : p))
    updatePiecesAndSave(newPieces)
  }
  
  const deletePiece = (id) => {
    const piece = pieces.find(p => p.id === id)
    if (piece?.isDemo) {
      toast.error("Cannot delete demo piece")
      return
    }
    const newPieces = pieces.filter(p => p.id !== id)
    updatePiecesAndSave(newPieces)
    toast.success("Piece removed from portfolio")
  }
  
  const router = useRouter()
  
  const editPiece = (piece) => {
    if (piece.isDemo) {
      toast.error("Cannot edit demo piece")
      return
    }
    if (piece.score) {
      toast.error("Cannot edit graded submissions")
      return
    }
    // Store the piece data for editing in the editor
    localStorage.setItem("newsroomlab_edit_submission", JSON.stringify(piece))
    // Navigate to editor with edit mode
    const templateId = piece.templateId || "default"
    router.push(`/dashboard/editor?template=${templateId}&edit=${piece.id}`)
    toast.success("Opening submission for editing...")
  }

  const realPieces = pieces.filter(p => !p.isDemo)
  const selectedCount = pieces.filter((p) => p.selected && !p.isDemo).length
  const scoredSelected = pieces.filter((p) => p.selected && p.score)
  const averageScore = scoredSelected.length > 0
    ? Math.round(scoredSelected.reduce((a, b) => a + (b.score || 0), 0) / scoredSelected.length)
    : 0

  const handleExportPDF = () => {
    if (selectedCount === 0) {
      toast.error("Select at least one piece to export.")
      return
    }
    const html = generatePortfolioHTML(pieces, user)
    const blob = new Blob([html], { type: "text/html" })
    const url = URL.createObjectURL(blob)
    const printWindow = window.open(url, "_blank")
    if (printWindow) {
      printWindow.onload = () => {
        setTimeout(() => printWindow.print(), 500)
      }
      toast.success(`Portfolio with ${selectedCount} piece${selectedCount !== 1 ? "s" : ""} opened for printing. Use "Save as PDF" in the print dialog.`)
    } else {
      // Fallback: download as HTML
      const a = document.createElement("a")
      a.href = url
      a.download = `portfolio-${user?.name?.replace(/\s+/g, "-").toLowerCase() || "student"}-${new Date().toISOString().slice(0, 10)}.html`
      a.click()
      toast.success("Portfolio downloaded as HTML. Open it in a browser and print to PDF.")
    }
  }

  return (
    <div className="space-y-8">
      <div className="flex items-start justify-between">
        <div>
          <h1 className="text-2xl font-bold tracking-tight flex items-center gap-2">
            <Briefcase className="h-6 w-6" />
            My Portfolio
          </h1>
          <p className="text-muted-foreground">
            Select your best pieces and export a professional portfolio PDF.
          </p>
        </div>
        <Button
          className="gap-2"
          onClick={handleExportPDF}
          disabled={selectedCount === 0}
        >
          <Download className="h-4 w-4" />
          Export PDF ({selectedCount})
        </Button>
      </div>

      {/* Portfolio Stats */}
      <div className="grid gap-4 md:grid-cols-3">
        <Card>
          <CardContent className="p-4">
            <p className="text-xs text-muted-foreground">Selected Pieces</p>
            <p className="text-2xl font-bold">{selectedCount}</p>
          </CardContent>
        </Card>
        <Card>
          <CardContent className="p-4">
            <p className="text-xs text-muted-foreground">Average Score</p>
            <p className="text-2xl font-bold">{averageScore}%</p>
            <Progress value={averageScore} className="h-1.5 mt-2" />
          </CardContent>
        </Card>
        <Card>
          <CardContent className="p-4">
            <p className="text-xs text-muted-foreground">Story Types</p>
            <div className="flex flex-wrap gap-1 mt-1">
              {[...new Set(pieces.filter((p) => p.selected).map((p) => p.storyType))].map(
                (type) => (
                  <Badge key={type} variant="secondary" className="text-xs">
                    {STORY_TYPE_LABELS[type]}
                  </Badge>
                )
              )}
            </div>
          </CardContent>
        </Card>
      </div>

      <Separator />

      {/* Portfolio Pieces */}
      <div className="space-y-4">
        <div className="flex items-center justify-between">
          <h2 className="font-semibold">Your Pieces ({realPieces.length})</h2>
          {realPieces.length === 0 && (
            <Badge variant="outline">Submit stories in the Editor to build your portfolio</Badge>
          )}
        </div>
        
        {loading ? (
          <Card>
            <CardContent className="p-8 text-center text-muted-foreground">
              Loading portfolio...
            </CardContent>
          </Card>
        ) : realPieces.length === 0 ? (
          <Card>
            <CardContent className="p-8 text-center">
              <Briefcase className="h-12 w-12 mx-auto mb-4 text-muted-foreground" />
              <h3 className="font-semibold mb-2">No submissions yet</h3>
              <p className="text-muted-foreground text-sm mb-4">
                Complete and submit stories in the Editor to add them to your portfolio.
              </p>
              <Button variant="outline" asChild>
                <a href="/dashboard/assignments">View Assignments</a>
              </Button>
            </CardContent>
          </Card>
        ) : (
          pieces.filter(p => !p.isDemo).map((piece) => (
            <Card
              key={piece.id}
              className={`transition-all ${
                piece.selected ? "ring-2 ring-blue-500 ring-offset-2 dark:ring-offset-zinc-950" : ""
              }`}
            >
              <CardContent className="p-6">
                <div className="flex items-start gap-4">
                  <div className="pt-1">
                    <Checkbox
                      checked={piece.selected}
                      onCheckedChange={() => togglePiece(piece.id)}
                      className="h-5 w-5"
                    />
                  </div>
                  <div className="flex-1">
                    <div className="flex items-start justify-between">
                      <div>
                        <h3 className="font-semibold">{piece.title || piece.headline || "Untitled Story"}</h3>
                        <div className="flex items-center gap-2 mt-1 flex-wrap">
                          <Badge variant="secondary" className="text-xs">
                            {STORY_TYPE_LABELS[piece.storyType] || piece.storyType}
                          </Badge>
                          <span className="text-xs text-muted-foreground">
                            {piece.course} — {piece.date}
                          </span>
                          {piece.editCount > 0 && (
                            <Badge variant="outline" className="text-xs text-blue-600 border-blue-200">
                              <RotateCcw className="h-3 w-3 mr-1" />
                              Edited
                            </Badge>
                          )}
                        </div>
                      </div>
                      <div className="flex items-center gap-2">
                        {piece.score ? (
                          <div className="flex items-center gap-1">
                            <Star className="h-4 w-4 text-amber-500" />
                            <span className="font-bold">{piece.score}%</span>
                          </div>
                        ) : (
                          <>
                            <Badge variant="outline" className="text-xs">Awaiting Grade</Badge>
                            <Button 
                              variant="ghost" 
                              size="icon" 
                              className="h-8 w-8 text-muted-foreground hover:text-blue-600"
                              onClick={() => editPiece(piece)}
                              title="Edit submission"
                            >
                              <Pencil className="h-4 w-4" />
                            </Button>
                          </>
                        )}
                        <Button 
                          variant="ghost" 
                          size="icon" 
                          className="h-8 w-8 text-muted-foreground hover:text-red-600"
                          onClick={() => deletePiece(piece.id)}
                          title="Remove from portfolio"
                        >
                          <Trash2 className="h-4 w-4" />
                        </Button>
                      </div>
                    </div>
                    
                    {/* Preview of content */}
                    {piece.draftContent && (
                      <p className="text-sm text-muted-foreground mt-2 line-clamp-2">
                        {piece.draftContent.slice(0, 200)}...
                      </p>
                    )}

                    <div className="mt-3 flex items-center gap-4 text-xs text-muted-foreground flex-wrap">
                      <div className="flex items-center gap-1">
                        <CheckCircle2 className="h-3.5 w-3.5 text-green-600" />
                        {piece.verifications || 0} verifications
                      </div>
                      <div className="flex items-center gap-1">
                        <FileText className="h-3.5 w-3.5" />
                        Submitted {piece.submittedAt ? new Date(piece.submittedAt).toLocaleDateString() : piece.date}
                      </div>
                      {piece.reflectionAnswers && Object.keys(piece.reflectionAnswers).length > 0 && (
                        <div className="flex items-center gap-1">
                          <Eye className="h-3.5 w-3.5" />
                          Reflection included
                        </div>
                      )}
                    </div>
                  </div>
                </div>
              </CardContent>
            </Card>
          ))
        )}
      </div>

      {/* Portfolio Contents Preview */}
      <Card>
        <CardHeader>
          <CardTitle className="text-base">Portfolio PDF Contents</CardTitle>
          <CardDescription>
            Your exported portfolio will include these sections for each selected piece.
          </CardDescription>
        </CardHeader>
        <CardContent>
          <ul className="space-y-2">
            {[
              "Cover page (name, course, semester)",
              "Title, story type, and date for each piece",
              "Final story text",
              "Verification table summary",
              "Ethics memo (if applicable)",
              "Student reflection",
              "Evidence appendix (source links and attachments)",
            ].map((item, i) => (
              <li key={i} className="flex items-center gap-2 text-sm">
                <CheckCircle2 className="h-4 w-4 text-green-600 shrink-0" />
                {item}
              </li>
            ))}
          </ul>
        </CardContent>
      </Card>
    </div>
  )
}
