"use client"

import { useState } from "react"
import {
  Briefcase,
  FileText,
  Download,
  CheckCircle2,
  Star,
  Eye,
} from "lucide-react"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import { Checkbox } from "@/components/ui/checkbox"
import { Progress } from "@/components/ui/progress"
import { Separator } from "@/components/ui/separator"
import { useAuth } from "@/components/providers/auth-provider"
import { toast } from "sonner"
import { STORY_TYPE_LABELS } from "@/lib/types"

const initialPortfolioPieces = [
  {
    id: "1",
    title: "Nairobi Allocates Ksh 38.7B in New Budget",
    storyType: "HARD_NEWS",
    course: "HCC 314",
    date: "March 2026",
    score: 78,
    verifications: 10,
    selected: true,
  },
  {
    id: "2",
    title: "Silent Struggle: Student Mental Health Crisis",
    storyType: "FEATURE",
    course: "HCC 314",
    date: "March 2026",
    score: 82,
    verifications: 12,
    selected: true,
  },
  {
    id: "3",
    title: "The Corruption Trial: Day One",
    storyType: "COURTS",
    course: "HCC 314",
    date: "April 2026",
    score: undefined,
    verifications: 6,
    selected: false,
  },
]

function generatePortfolioHTML(pieces, user) {
  const selected = pieces.filter((p) => p.selected)
  return `<!DOCTYPE html>
<html><head><meta charset="utf-8"><title>Portfolio — ${user?.name || "Student"}</title>
<style>
  body { font-family: Georgia, serif; max-width: 800px; margin: 40px auto; color: #1a1a1a; line-height: 1.6; }
  h1 { font-size: 28px; border-bottom: 3px solid #1a1a1a; padding-bottom: 12px; }
  h2 { font-size: 20px; margin-top: 40px; color: #333; }
  .meta { color: #666; font-size: 14px; margin-bottom: 8px; }
  .piece { page-break-inside: avoid; margin-bottom: 40px; padding: 20px; border: 1px solid #e5e5e5; border-radius: 8px; }
  .badge { display: inline-block; background: #f0f0f0; padding: 2px 8px; border-radius: 4px; font-size: 12px; margin-right: 4px; }
  .score { float: right; font-size: 24px; font-weight: bold; color: #166534; }
  .section-label { font-weight: bold; font-size: 13px; text-transform: uppercase; letter-spacing: 1px; color: #666; margin-top: 16px; }
  .footer { margin-top: 60px; text-align: center; font-size: 12px; color: #999; border-top: 1px solid #e5e5e5; padding-top: 12px; }
  @media print { body { margin: 20px; } .piece { border: none; border-bottom: 1px solid #ccc; } }
</style></head><body>
<h1>Journalism Portfolio</h1>
<p class="meta"><strong>${user?.name || "Student Name"}</strong> · ${user?.email || ""} · ${new Date().toLocaleDateString("en-GB", { month: "long", year: "numeric" })}</p>
<p class="meta">${selected.length} selected piece${selected.length !== 1 ? "s" : ""} · Generated from NewsroomLab AI</p>
<hr>
${selected.map((p, i) => `
<div class="piece">
  ${p.score ? `<div class="score">${p.score}%</div>` : ""}
  <h2>${i + 1}. ${p.title}</h2>
  <p class="meta">
    <span class="badge">${STORY_TYPE_LABELS[p.storyType] || p.storyType}</span>
    <span class="badge">${p.course}</span>
    ${p.date}
  </p>
  <p class="section-label">Verification</p>
  <p>${p.verifications} claims independently verified</p>
  <p class="section-label">Reflection</p>
  <p><em>Reflection included in submission</em></p>
</div>`).join("\n")}
<div class="footer">
  <p>This portfolio was generated by NewsroomLab AI on ${new Date().toLocaleDateString("en-GB", { day: "numeric", month: "long", year: "numeric" })}.</p>
  <p>All stories include verification tables, AI disclosure, and student reflections.</p>
</div>
</body></html>`
}

export default function PortfolioPage() {
  const { user } = useAuth()
  const [pieces, setPieces] = useState(initialPortfolioPieces)

  const togglePiece = (id) => {
    setPieces((prev) =>
      prev.map((p) => (p.id === id ? { ...p, selected: !p.selected } : p))
    )
  }

  const selectedCount = pieces.filter((p) => p.selected).length
  const scoredSelected = pieces.filter((p) => p.selected && p.score)
  const averageScore = scoredSelected.length > 0
    ? Math.round(scoredSelected.reduce((a, b) => a + (b.score || 0), 0) / scoredSelected.length)
    : 0

  const handleExportPDF = () => {
    if (selectedCount === 0) {
      toast.error("Select at least one piece to export.")
      return
    }
    const html = generatePortfolioHTML(pieces, user)
    const blob = new Blob([html], { type: "text/html" })
    const url = URL.createObjectURL(blob)
    const printWindow = window.open(url, "_blank")
    if (printWindow) {
      printWindow.onload = () => {
        setTimeout(() => printWindow.print(), 500)
      }
      toast.success(`Portfolio with ${selectedCount} piece${selectedCount !== 1 ? "s" : ""} opened for printing. Use "Save as PDF" in the print dialog.`)
    } else {
      // Fallback: download as HTML
      const a = document.createElement("a")
      a.href = url
      a.download = `portfolio-${user?.name?.replace(/\s+/g, "-").toLowerCase() || "student"}-${new Date().toISOString().slice(0, 10)}.html`
      a.click()
      toast.success("Portfolio downloaded as HTML. Open it in a browser and print to PDF.")
    }
  }

  return (
    <div className="space-y-8">
      <div className="flex items-start justify-between">
        <div>
          <h1 className="text-2xl font-bold tracking-tight flex items-center gap-2">
            <Briefcase className="h-6 w-6" />
            My Portfolio
          </h1>
          <p className="text-muted-foreground">
            Select your best pieces and export a professional portfolio PDF.
          </p>
        </div>
        <Button
          className="gap-2"
          onClick={handleExportPDF}
          disabled={selectedCount === 0}
        >
          <Download className="h-4 w-4" />
          Export PDF ({selectedCount})
        </Button>
      </div>

      {/* Portfolio Stats */}
      <div className="grid gap-4 md:grid-cols-3">
        <Card>
          <CardContent className="p-4">
            <p className="text-xs text-muted-foreground">Selected Pieces</p>
            <p className="text-2xl font-bold">{selectedCount}</p>
          </CardContent>
        </Card>
        <Card>
          <CardContent className="p-4">
            <p className="text-xs text-muted-foreground">Average Score</p>
            <p className="text-2xl font-bold">{averageScore}%</p>
            <Progress value={averageScore} className="h-1.5 mt-2" />
          </CardContent>
        </Card>
        <Card>
          <CardContent className="p-4">
            <p className="text-xs text-muted-foreground">Story Types</p>
            <div className="flex flex-wrap gap-1 mt-1">
              {[...new Set(pieces.filter((p) => p.selected).map((p) => p.storyType))].map(
                (type) => (
                  <Badge key={type} variant="secondary" className="text-xs">
                    {STORY_TYPE_LABELS[type]}
                  </Badge>
                )
              )}
            </div>
          </CardContent>
        </Card>
      </div>

      <Separator />

      {/* Portfolio Pieces */}
      <div className="space-y-4">
        <h2 className="font-semibold">Your Pieces</h2>
        {pieces.map((piece) => (
          <Card
            key={piece.id}
            className={`transition-all ${
              piece.selected ? "ring-2 ring-blue-500 ring-offset-2 dark:ring-offset-zinc-950" : ""
            }`}
          >
            <CardContent className="p-6">
              <div className="flex items-start gap-4">
                <div className="pt-1">
                  <Checkbox
                    checked={piece.selected}
                    onCheckedChange={() => togglePiece(piece.id)}
                    className="h-5 w-5"
                  />
                </div>
                <div className="flex-1">
                  <div className="flex items-start justify-between">
                    <div>
                      <h3 className="font-semibold">{piece.title}</h3>
                      <div className="flex items-center gap-2 mt-1">
                        <Badge variant="secondary" className="text-xs">
                          {STORY_TYPE_LABELS[piece.storyType]}
                        </Badge>
                        <span className="text-xs text-muted-foreground">
                          {piece.course} — {piece.date}
                        </span>
                      </div>
                    </div>
                    <div className="text-right">
                      {piece.score ? (
                        <div className="flex items-center gap-1">
                          <Star className="h-4 w-4 text-amber-500" />
                          <span className="font-bold">{piece.score}%</span>
                        </div>
                      ) : (
                        <Badge variant="outline" className="text-xs">Pending</Badge>
                      )}
                    </div>
                  </div>

                  <div className="mt-3 flex items-center gap-4 text-xs text-muted-foreground">
                    <div className="flex items-center gap-1">
                      <CheckCircle2 className="h-3.5 w-3.5 text-green-600" />
                      {piece.verifications} verifications
                    </div>
                    <div className="flex items-center gap-1">
                      <FileText className="h-3.5 w-3.5" />
                      Final version submitted
                    </div>
                    <div className="flex items-center gap-1">
                      <Eye className="h-3.5 w-3.5" />
                      Reflection included
                    </div>
                  </div>
                </div>
              </div>
            </CardContent>
          </Card>
        ))}
      </div>

      {/* Portfolio Contents Preview */}
      <Card>
        <CardHeader>
          <CardTitle className="text-base">Portfolio PDF Contents</CardTitle>
          <CardDescription>
            Your exported portfolio will include these sections for each selected piece.
          </CardDescription>
        </CardHeader>
        <CardContent>
          <ul className="space-y-2">
            {[
              "Cover page (name, course, semester)",
              "Title, story type, and date for each piece",
              "Final story text",
              "Verification table summary",
              "Ethics memo (if applicable)",
              "Student reflection",
              "Evidence appendix (source links and attachments)",
            ].map((item, i) => (
              <li key={i} className="flex items-center gap-2 text-sm">
                <CheckCircle2 className="h-4 w-4 text-green-600 shrink-0" />
                {item}
              </li>
            ))}
          </ul>
        </CardContent>
      </Card>
    </div>
  )
}
