// ─── NewsroomLab AI — Rubric Presets ────────────────────
// Rubrics per genre/story type. Each rubric has weighted categories.

export const rubricPresets = {
  // ═══════════════════════════════════════════════════════
  // Hard News Rubric
  // ═══════════════════════════════════════════════════════
  hard_news_rubric: {
    id: "hard_news_rubric",
    name: "Hard News Rubric",
    totalPoints: 100,
    categories: [
      {
        key: "news_value",
        label: "News Value & Focus",
        description: "Is the story newsworthy? Is the angle clear and focused?",
        maxPoints: 10,
        levels: [
          { score: 10, label: "Excellent", description: "Strong news value, clear focused angle" },
          { score: 7, label: "Good", description: "Solid news value, mostly focused" },
          { score: 5, label: "Adequate", description: "Some news value, angle unclear" },
          { score: 3, label: "Weak", description: "Limited news value, unfocused" },
          { score: 0, label: "Missing", description: "No clear news value" },
        ],
      },
      {
        key: "lead_structure",
        label: "Lead & Structure",
        description: "Is the lead compelling and accurate? Is the inverted pyramid applied correctly?",
        maxPoints: 15,
        levels: [
          { score: 15, label: "Excellent", description: "Sharp lead, perfect structure, smooth flow" },
          { score: 11, label: "Good", description: "Effective lead, solid structure" },
          { score: 8, label: "Adequate", description: "Serviceable lead, some structural issues" },
          { score: 4, label: "Weak", description: "Buried lead or poor structure" },
          { score: 0, label: "Missing", description: "No recognisable news structure" },
        ],
      },
      {
        key: "attribution",
        label: "Attribution & Sourcing",
        description: "Are all claims attributed? Are sources credible and diverse?",
        maxPoints: 15,
        levels: [
          { score: 15, label: "Excellent", description: "All claims attributed, diverse credible sources" },
          { score: 11, label: "Good", description: "Most claims attributed, good sources" },
          { score: 8, label: "Adequate", description: "Some attribution gaps" },
          { score: 4, label: "Weak", description: "Significant attribution problems" },
          { score: 0, label: "Missing", description: "No attribution" },
        ],
      },
      {
        key: "accuracy",
        label: "Accuracy & Verification Discipline",
        description: "Are facts verified? Is the verification table complete?",
        maxPoints: 20,
        levels: [
          { score: 20, label: "Excellent", description: "All claims verified, complete evidence chain" },
          { score: 15, label: "Good", description: "Most claims verified, minor gaps" },
          { score: 10, label: "Adequate", description: "Some verification effort, notable gaps" },
          { score: 5, label: "Weak", description: "Minimal verification" },
          { score: 0, label: "Missing", description: "No verification evidence" },
        ],
      },
      {
        key: "language",
        label: "Language & Style",
        description: "Is the writing clear, concise, and appropriate for news?",
        maxPoints: 10,
        levels: [
          { score: 10, label: "Excellent", description: "Clean, professional prose" },
          { score: 7, label: "Good", description: "Mostly clean, minor style issues" },
          { score: 5, label: "Adequate", description: "Readable but needs editing" },
          { score: 3, label: "Weak", description: "Significant language issues" },
          { score: 0, label: "Missing", description: "Unreadable" },
        ],
      },
      {
        key: "ethics",
        label: "Ethics & Legal Compliance",
        description: "Are ethical standards met? Any legal risks?",
        maxPoints: 10,
        levels: [
          { score: 10, label: "Excellent", description: "Fully compliant, ethics considered" },
          { score: 7, label: "Good", description: "Mostly compliant, minor oversights" },
          { score: 5, label: "Adequate", description: "Some ethical awareness" },
          { score: 3, label: "Weak", description: "Ethical concerns present" },
          { score: 0, label: "Missing", description: "Serious ethical/legal issues" },
        ],
      },
      {
        key: "reflection",
        label: "Media Studies Reflection",
        description: "Quality of framing analysis and critical reflection",
        maxPoints: 10,
        levels: [
          { score: 10, label: "Excellent", description: "Deep, nuanced critical reflection" },
          { score: 7, label: "Good", description: "Solid reflection with some depth" },
          { score: 5, label: "Adequate", description: "Surface-level reflection" },
          { score: 3, label: "Weak", description: "Minimal reflection" },
          { score: 0, label: "Missing", description: "No reflection submitted" },
        ],
      },
      {
        key: "revision",
        label: "Revision Quality",
        description: "How well did the student respond to AI and peer feedback?",
        maxPoints: 10,
        levels: [
          { score: 10, label: "Excellent", description: "Significant, thoughtful revisions" },
          { score: 7, label: "Good", description: "Good revision effort" },
          { score: 5, label: "Adequate", description: "Some revisions made" },
          { score: 3, label: "Weak", description: "Minimal revision" },
          { score: 0, label: "Missing", description: "No revision from v1" },
        ],
      },
    ],
  },

  // ═══════════════════════════════════════════════════════
  // Courts / Legal Reporting Rubric
  // ═══════════════════════════════════════════════════════
  courts_rubric: {
    id: "courts_rubric",
    name: "Courts / Legal Reporting Rubric",
    totalPoints: 100,
    categories: [
      { key: "legal_accuracy", label: "Legal Accuracy", description: "Are legal proceedings reported accurately? Correct terminology?", maxPoints: 20,
        levels: [
          { score: 20, label: "Excellent", description: "Legally precise, correct terminology throughout" },
          { score: 15, label: "Good", description: "Mostly accurate, minor terminology issues" },
          { score: 10, label: "Adequate", description: "Some legal inaccuracies" },
          { score: 5, label: "Weak", description: "Significant legal errors" },
          { score: 0, label: "Missing", description: "Legally inaccurate or misleading" },
        ],
      },
      { key: "sub_judice", label: "Sub Judice Compliance", description: "Does the report respect sub judice rules and fair trial rights?", maxPoints: 20,
        levels: [
          { score: 20, label: "Excellent", description: "Full compliance, careful language" },
          { score: 15, label: "Good", description: "Mostly compliant, minor concerns" },
          { score: 10, label: "Adequate", description: "Some compliance issues" },
          { score: 5, label: "Weak", description: "Potential contempt issues" },
          { score: 0, label: "Dangerous", description: "Clear sub judice violations" },
        ],
      },
      { key: "balance", label: "Balance (Prosecution & Defence)", description: "Are both sides reported fairly?", maxPoints: 15,
        levels: [
          { score: 15, label: "Excellent", description: "Both sides fairly represented" },
          { score: 11, label: "Good", description: "Mostly balanced" },
          { score: 8, label: "Adequate", description: "Some imbalance" },
          { score: 4, label: "Weak", description: "One-sided reporting" },
          { score: 0, label: "Missing", description: "Only one side presented" },
        ],
      },
      { key: "attribution", label: "Attribution", description: "All testimony properly attributed?", maxPoints: 15,
        levels: [
          { score: 15, label: "Excellent", description: "All claims properly attributed to court proceedings" },
          { score: 11, label: "Good", description: "Most attribution correct" },
          { score: 8, label: "Adequate", description: "Some attribution gaps" },
          { score: 4, label: "Weak", description: "Significant gaps" },
          { score: 0, label: "Missing", description: "No attribution" },
        ],
      },
      { key: "structure", label: "Structure & Clarity", description: "Is the report well-structured and clear?", maxPoints: 10,
        levels: [
          { score: 10, label: "Excellent", description: "Clear, well-organised" },
          { score: 7, label: "Good", description: "Mostly clear" },
          { score: 5, label: "Adequate", description: "Readable but disorganised" },
          { score: 3, label: "Weak", description: "Confusing structure" },
          { score: 0, label: "Missing", description: "Unreadable" },
        ],
      },
      { key: "ethics_memo", label: "Ethics Memo Quality", description: "Quality of ethical reasoning in the memo", maxPoints: 10,
        levels: [
          { score: 10, label: "Excellent", description: "Thorough ethical reasoning" },
          { score: 7, label: "Good", description: "Solid ethics consideration" },
          { score: 5, label: "Adequate", description: "Basic ethics awareness" },
          { score: 3, label: "Weak", description: "Minimal ethics reflection" },
          { score: 0, label: "Missing", description: "No ethics memo" },
        ],
      },
      { key: "revision", label: "Revision Quality", description: "Response to AI feedback", maxPoints: 10,
        levels: [
          { score: 10, label: "Excellent", description: "Thoughtful, substantive revision" },
          { score: 7, label: "Good", description: "Good revision effort" },
          { score: 5, label: "Adequate", description: "Some revisions" },
          { score: 3, label: "Weak", description: "Minimal revision" },
          { score: 0, label: "Missing", description: "No revision" },
        ],
      },
    ],
  },

  // ═══════════════════════════════════════════════════════
  // Feature / Magazine Rubric
  // ═══════════════════════════════════════════════════════
  feature_rubric: {
    id: "feature_rubric",
    name: "Feature / Magazine Rubric",
    totalPoints: 100,
    categories: [
      { key: "narrative", label: "Narrative & Scene-Setting", description: "Does the story open with a compelling scene? Is show-don't-tell applied?", maxPoints: 15,
        levels: [
          { score: 15, label: "Excellent", description: "Vivid scene-setting, immersive narrative" },
          { score: 11, label: "Good", description: "Good narrative with some vivid moments" },
          { score: 8, label: "Adequate", description: "Attempts narrative but falls flat" },
          { score: 4, label: "Weak", description: "Reads like a news story, no narrative" },
          { score: 0, label: "Missing", description: "No narrative elements" },
        ],
      },
      { key: "nut_graf", label: "Nut Graf & Focus", description: "Is the 'so what' clear? Does the reader know why this matters?", maxPoints: 10,
        levels: [
          { score: 10, label: "Excellent", description: "Crystal clear nut graf, compelling focus" },
          { score: 7, label: "Good", description: "Clear nut graf" },
          { score: 5, label: "Adequate", description: "Nut graf present but weak" },
          { score: 3, label: "Weak", description: "Unclear focus" },
          { score: 0, label: "Missing", description: "No nut graf" },
        ],
      },
      { key: "sourcing", label: "Sourcing & Voices", description: "Are multiple voices heard? Are sources diverse?", maxPoints: 15,
        levels: [
          { score: 15, label: "Excellent", description: "Rich, diverse voices, deep interviews" },
          { score: 11, label: "Good", description: "Multiple good sources" },
          { score: 8, label: "Adequate", description: "Minimum sources met" },
          { score: 4, label: "Weak", description: "Too few sources" },
          { score: 0, label: "Missing", description: "No sources" },
        ],
      },
      { key: "accuracy", label: "Accuracy & Verification", description: "Are facts verified?", maxPoints: 15,
        levels: [
          { score: 15, label: "Excellent", description: "All facts verified" },
          { score: 11, label: "Good", description: "Most facts verified" },
          { score: 8, label: "Adequate", description: "Some verification" },
          { score: 4, label: "Weak", description: "Minimal verification" },
          { score: 0, label: "Missing", description: "No verification" },
        ],
      },
      { key: "language", label: "Language, Style & Pacing", description: "Quality of prose, pacing, and readability", maxPoints: 15,
        levels: [
          { score: 15, label: "Excellent", description: "Beautiful, polished prose with excellent pacing" },
          { score: 11, label: "Good", description: "Strong writing, good flow" },
          { score: 8, label: "Adequate", description: "Readable, some style issues" },
          { score: 4, label: "Weak", description: "Flat or clunky prose" },
          { score: 0, label: "Missing", description: "Unreadable" },
        ],
      },
      { key: "ethics", label: "Ethics & Sensitivity", description: "Ethical handling of vulnerable subjects, consent, representation", maxPoints: 10,
        levels: [
          { score: 10, label: "Excellent", description: "Exemplary ethical judgment" },
          { score: 7, label: "Good", description: "Good ethical awareness" },
          { score: 5, label: "Adequate", description: "Basic awareness" },
          { score: 3, label: "Weak", description: "Ethical concerns" },
          { score: 0, label: "Missing", description: "Serious ethical issues" },
        ],
      },
      { key: "reflection", label: "Reflection", description: "Quality of critical media reflection", maxPoints: 10,
        levels: [
          { score: 10, label: "Excellent", description: "Deep, nuanced reflection" },
          { score: 7, label: "Good", description: "Solid reflection" },
          { score: 5, label: "Adequate", description: "Surface-level" },
          { score: 3, label: "Weak", description: "Minimal" },
          { score: 0, label: "Missing", description: "None" },
        ],
      },
      { key: "revision", label: "Revision Quality", description: "Quality of revisions", maxPoints: 10,
        levels: [
          { score: 10, label: "Excellent", description: "Substantial, thoughtful revisions" },
          { score: 7, label: "Good", description: "Good effort" },
          { score: 5, label: "Adequate", description: "Some revision" },
          { score: 3, label: "Weak", description: "Minimal" },
          { score: 0, label: "Missing", description: "None" },
        ],
      },
    ],
  },

  // ═══════════════════════════════════════════════════════
  // Broadcast Rubric
  // ═══════════════════════════════════════════════════════
  broadcast_rubric: {
    id: "broadcast_rubric",
    name: "Broadcast Rubric",
    totalPoints: 100,
    categories: [
      { key: "broadcast_style", label: "Broadcast Writing Style", description: "Is it written to be heard? Short sentences, active voice, conversational?", maxPoints: 20,
        levels: [
          { score: 20, label: "Excellent", description: "Natural broadcast style, write-to-be-heard" },
          { score: 15, label: "Good", description: "Mostly broadcast-appropriate" },
          { score: 10, label: "Adequate", description: "Mix of print and broadcast style" },
          { score: 5, label: "Weak", description: "Reads like print, not broadcast" },
          { score: 0, label: "Missing", description: "Not broadcast writing" },
        ],
      },
      { key: "accuracy", label: "Accuracy & Attribution", description: "Are facts accurate and attributed?", maxPoints: 20,
        levels: [
          { score: 20, label: "Excellent", description: "All facts verified and attributed" },
          { score: 15, label: "Good", description: "Mostly accurate" },
          { score: 10, label: "Adequate", description: "Some accuracy issues" },
          { score: 5, label: "Weak", description: "Significant issues" },
          { score: 0, label: "Missing", description: "Inaccurate" },
        ],
      },
      { key: "structure", label: "Package Structure", description: "Is the VO/SOT/PKG structure correct?", maxPoints: 20,
        levels: [
          { score: 20, label: "Excellent", description: "Professional package structure" },
          { score: 15, label: "Good", description: "Solid structure" },
          { score: 10, label: "Adequate", description: "Basic structure present" },
          { score: 5, label: "Weak", description: "Structural problems" },
          { score: 0, label: "Missing", description: "No recognisable structure" },
        ],
      },
      { key: "storytelling", label: "Storytelling & Engagement", description: "Does it hold the audience?", maxPoints: 15,
        levels: [
          { score: 15, label: "Excellent", description: "Compelling, engaging storytelling" },
          { score: 11, label: "Good", description: "Interesting, holds attention" },
          { score: 8, label: "Adequate", description: "Informative but dull" },
          { score: 4, label: "Weak", description: "Flat, loses audience" },
          { score: 0, label: "Missing", description: "No storytelling" },
        ],
      },
      { key: "technical", label: "Technical Elements", description: "Cue sheet, duration, shot list accuracy", maxPoints: 15,
        levels: [
          { score: 15, label: "Excellent", description: "Professional technical execution" },
          { score: 11, label: "Good", description: "Good technical elements" },
          { score: 8, label: "Adequate", description: "Basic technical elements present" },
          { score: 4, label: "Weak", description: "Missing technical elements" },
          { score: 0, label: "Missing", description: "No technical elements" },
        ],
      },
      { key: "revision", label: "Revision", description: "Response to feedback", maxPoints: 10,
        levels: [
          { score: 10, label: "Excellent", description: "Thoughtful revision" },
          { score: 7, label: "Good", description: "Good effort" },
          { score: 5, label: "Adequate", description: "Some revision" },
          { score: 3, label: "Weak", description: "Minimal" },
          { score: 0, label: "Missing", description: "None" },
        ],
      },
    ],
  },

  // ═══════════════════════════════════════════════════════
  // PR Writing Rubric
  // ═══════════════════════════════════════════════════════
  pr_writing_rubric: {
    id: "pr_writing_rubric",
    name: "PR Writing Rubric",
    totalPoints: 100,
    categories: [
      { key: "newsworthiness", label: "Newsworthiness & Angle", description: "Would a journalist use this? Is the angle clear?", maxPoints: 15,
        levels: [
          { score: 15, label: "Excellent", description: "Clearly newsworthy, strong angle" },
          { score: 11, label: "Good", description: "Newsworthy, decent angle" },
          { score: 8, label: "Adequate", description: "Some news value" },
          { score: 4, label: "Weak", description: "Not newsworthy" },
          { score: 0, label: "Missing", description: "Pure puffery" },
        ],
      },
      { key: "structure", label: "Structure & Format", description: "Does it follow the correct PR format?", maxPoints: 15,
        levels: [
          { score: 15, label: "Excellent", description: "Professional format, all elements present" },
          { score: 11, label: "Good", description: "Good format, minor omissions" },
          { score: 8, label: "Adequate", description: "Basic format" },
          { score: 4, label: "Weak", description: "Format problems" },
          { score: 0, label: "Missing", description: "Wrong format" },
        ],
      },
      { key: "accuracy", label: "Accuracy & Factual Claims", description: "Are all facts verifiable? No exaggeration?", maxPoints: 20,
        levels: [
          { score: 20, label: "Excellent", description: "All facts verifiable, no puffery" },
          { score: 15, label: "Good", description: "Mostly accurate" },
          { score: 10, label: "Adequate", description: "Some unverifiable claims" },
          { score: 5, label: "Weak", description: "Significant accuracy issues" },
          { score: 0, label: "Missing", description: "Unreliable" },
        ],
      },
      { key: "language", label: "Language & Tone", description: "Is the writing clear, professional, and audience-appropriate?", maxPoints: 15,
        levels: [
          { score: 15, label: "Excellent", description: "Professional, polished, audience-aware" },
          { score: 11, label: "Good", description: "Clear and professional" },
          { score: 8, label: "Adequate", description: "Readable" },
          { score: 4, label: "Weak", description: "Unclear or inappropriate tone" },
          { score: 0, label: "Missing", description: "Unprofessional" },
        ],
      },
      { key: "audience", label: "Audience Awareness", description: "Is it tailored to the target audience?", maxPoints: 15,
        levels: [
          { score: 15, label: "Excellent", description: "Perfectly targeted" },
          { score: 11, label: "Good", description: "Good audience awareness" },
          { score: 8, label: "Adequate", description: "Some awareness" },
          { score: 4, label: "Weak", description: "Generic, not targeted" },
          { score: 0, label: "Missing", description: "No audience awareness" },
        ],
      },
      { key: "ethics_transparency", label: "Ethics & Transparency", description: "Is it honest? No misleading spin?", maxPoints: 10,
        levels: [
          { score: 10, label: "Excellent", description: "Fully transparent and ethical" },
          { score: 7, label: "Good", description: "Mostly ethical" },
          { score: 5, label: "Adequate", description: "Some concerns" },
          { score: 3, label: "Weak", description: "Misleading elements" },
          { score: 0, label: "Missing", description: "Deliberately misleading" },
        ],
      },
      { key: "reflection", label: "Reflection", description: "Critical reflection on PR practice", maxPoints: 10,
        levels: [
          { score: 10, label: "Excellent", description: "Thoughtful reflection on PR ethics and power" },
          { score: 7, label: "Good", description: "Solid reflection" },
          { score: 5, label: "Adequate", description: "Surface-level" },
          { score: 3, label: "Weak", description: "Minimal" },
          { score: 0, label: "Missing", description: "None" },
        ],
      },
    ],
  },

  // ═══════════════════════════════════════════════════════
  // Editorial Rubric
  // ═══════════════════════════════════════════════════════
  editorial_rubric: {
    id: "editorial_rubric",
    name: "Editorial & Review Rubric",
    totalPoints: 100,
    categories: [
      { key: "thesis", label: "Thesis & Argument", description: "Is the position clear? Is the argument well-constructed?", maxPoints: 20,
        levels: [
          { score: 20, label: "Excellent", description: "Clear, bold thesis with sophisticated argument" },
          { score: 15, label: "Good", description: "Clear thesis, solid argument" },
          { score: 10, label: "Adequate", description: "Position stated but argument weak" },
          { score: 5, label: "Weak", description: "Unclear position" },
          { score: 0, label: "Missing", description: "No discernible thesis" },
        ],
      },
      { key: "evidence", label: "Evidence & Support", description: "Is the opinion supported by facts, data, and credible sources?", maxPoints: 20,
        levels: [
          { score: 20, label: "Excellent", description: "Strong, well-sourced evidence" },
          { score: 15, label: "Good", description: "Good evidence" },
          { score: 10, label: "Adequate", description: "Some evidence" },
          { score: 5, label: "Weak", description: "Unsupported opinion" },
          { score: 0, label: "Missing", description: "Pure assertion, no evidence" },
        ],
      },
      { key: "counterargument", label: "Counterargument", description: "Does the writer engage with opposing views fairly?", maxPoints: 15,
        levels: [
          { score: 15, label: "Excellent", description: "Strong counterargument engaged and rebutted" },
          { score: 11, label: "Good", description: "Counterargument acknowledged and addressed" },
          { score: 8, label: "Adequate", description: "Brief mention of other views" },
          { score: 4, label: "Weak", description: "Straw man or dismissive" },
          { score: 0, label: "Missing", description: "No counterargument" },
        ],
      },
      { key: "language", label: "Language & Voice", description: "Is the writing compelling, clear, and appropriately toned?", maxPoints: 15,
        levels: [
          { score: 15, label: "Excellent", description: "Distinctive voice, powerful prose" },
          { score: 11, label: "Good", description: "Strong voice, clear writing" },
          { score: 8, label: "Adequate", description: "Readable" },
          { score: 4, label: "Weak", description: "Flat or inappropriate tone" },
          { score: 0, label: "Missing", description: "Unreadable" },
        ],
      },
      { key: "accuracy", label: "Factual Accuracy", description: "Are all factual claims in the opinion piece accurate?", maxPoints: 10,
        levels: [
          { score: 10, label: "Excellent", description: "All facts accurate and verified" },
          { score: 7, label: "Good", description: "Mostly accurate" },
          { score: 5, label: "Adequate", description: "Some inaccuracies" },
          { score: 3, label: "Weak", description: "Significant factual errors" },
          { score: 0, label: "Missing", description: "Factually unreliable" },
        ],
      },
      { key: "reflection", label: "Media Theory Application", description: "Quality of media theory analysis (agenda-setting, gatekeeping, framing)", maxPoints: 10,
        levels: [
          { score: 10, label: "Excellent", description: "Sophisticated application of media theory" },
          { score: 7, label: "Good", description: "Good theory application" },
          { score: 5, label: "Adequate", description: "Basic theory reference" },
          { score: 3, label: "Weak", description: "Minimal theory" },
          { score: 0, label: "Missing", description: "No theory applied" },
        ],
      },
      { key: "revision", label: "Revision Quality", description: "Response to feedback", maxPoints: 10,
        levels: [
          { score: 10, label: "Excellent", description: "Thoughtful revision" },
          { score: 7, label: "Good", description: "Good effort" },
          { score: 5, label: "Adequate", description: "Some revision" },
          { score: 3, label: "Weak", description: "Minimal" },
          { score: 0, label: "Missing", description: "None" },
        ],
      },
    ],
  },

  // ═══════════════════════════════════════════════════════
  // Investigative Rubric
  // ═══════════════════════════════════════════════════════
  investigative_rubric: {
    id: "investigative_rubric",
    name: "Investigative Reporting Rubric",
    totalPoints: 100,
    categories: [
      { key: "revelation", label: "Original Revelation / Finding", description: "Does the story reveal something new and significant?", maxPoints: 15,
        levels: [
          { score: 15, label: "Excellent", description: "Significant original revelation" },
          { score: 11, label: "Good", description: "New information of value" },
          { score: 8, label: "Adequate", description: "Some new information" },
          { score: 4, label: "Weak", description: "Mostly rehashed information" },
          { score: 0, label: "Missing", description: "Nothing new" },
        ],
      },
      { key: "evidence_chain", label: "Evidence Chain & Documentation", description: "Is the evidence trail rigorous and documented?", maxPoints: 25,
        levels: [
          { score: 25, label: "Excellent", description: "Bulletproof evidence chain, multiple sources" },
          { score: 19, label: "Good", description: "Strong evidence, well-documented" },
          { score: 13, label: "Adequate", description: "Some documentation gaps" },
          { score: 6, label: "Weak", description: "Thin evidence" },
          { score: 0, label: "Missing", description: "No documentation" },
        ],
      },
      { key: "fairness", label: "Fairness & Right of Reply", description: "Was the subject given fair opportunity to respond?", maxPoints: 15,
        levels: [
          { score: 15, label: "Excellent", description: "Full right of reply, fair treatment" },
          { score: 11, label: "Good", description: "Right of reply sought" },
          { score: 8, label: "Adequate", description: "Attempted but insufficient" },
          { score: 4, label: "Weak", description: "Minimal effort" },
          { score: 0, label: "Missing", description: "No right of reply" },
        ],
      },
      { key: "public_interest", label: "Public Interest Justification", description: "Is the public interest case clear?", maxPoints: 10,
        levels: [
          { score: 10, label: "Excellent", description: "Clear, compelling public interest case" },
          { score: 7, label: "Good", description: "Solid justification" },
          { score: 5, label: "Adequate", description: "Some justification" },
          { score: 3, label: "Weak", description: "Weak justification" },
          { score: 0, label: "Missing", description: "No public interest case" },
        ],
      },
      { key: "structure", label: "Structure & Narrative", description: "Is the story well-organised and compelling?", maxPoints: 10,
        levels: [
          { score: 10, label: "Excellent", description: "Compelling, clear structure" },
          { score: 7, label: "Good", description: "Well-organised" },
          { score: 5, label: "Adequate", description: "Readable" },
          { score: 3, label: "Weak", description: "Confusing" },
          { score: 0, label: "Missing", description: "No structure" },
        ],
      },
      { key: "ethics", label: "Ethics & Legal Compliance", description: "Are ethical standards met?", maxPoints: 15,
        levels: [
          { score: 15, label: "Excellent", description: "Exemplary ethical standards" },
          { score: 11, label: "Good", description: "Ethical, minor concerns" },
          { score: 8, label: "Adequate", description: "Some ethical issues" },
          { score: 4, label: "Weak", description: "Significant concerns" },
          { score: 0, label: "Missing", description: "Serious ethical violations" },
        ],
      },
      { key: "revision", label: "Revision Quality", description: "Response to AI and editor feedback", maxPoints: 10,
        levels: [
          { score: 10, label: "Excellent", description: "Thoughtful revision" },
          { score: 7, label: "Good", description: "Good effort" },
          { score: 5, label: "Adequate", description: "Some revision" },
          { score: 3, label: "Weak", description: "Minimal" },
          { score: 0, label: "Missing", description: "None" },
        ],
      },
    ],
  },

  // ═══════════════════════════════════════════════════════
  // Digital / Online Rubric
  // ═══════════════════════════════════════════════════════
  digital_rubric: {
    id: "digital_rubric",
    name: "Digital / Online Journalism Rubric",
    totalPoints: 100,
    categories: [
      { key: "digital_first", label: "Digital-First Approach", description: "Is the content optimised for digital consumption?", maxPoints: 15,
        levels: [
          { score: 15, label: "Excellent", description: "Fully digital-native content" },
          { score: 11, label: "Good", description: "Good digital awareness" },
          { score: 8, label: "Adequate", description: "Some digital elements" },
          { score: 4, label: "Weak", description: "Print-first thinking" },
          { score: 0, label: "Missing", description: "Not digital at all" },
        ],
      },
      { key: "accuracy", label: "Accuracy & Verification", description: "Are facts verified, especially from social/online sources?", maxPoints: 20,
        levels: [
          { score: 20, label: "Excellent", description: "Rigorous verification" },
          { score: 15, label: "Good", description: "Well-verified" },
          { score: 10, label: "Adequate", description: "Some verification" },
          { score: 5, label: "Weak", description: "Insufficient verification" },
          { score: 0, label: "Missing", description: "Unverified" },
        ],
      },
      { key: "multimedia", label: "Multimedia Integration", description: "Effective use of multimedia elements?", maxPoints: 15,
        levels: [
          { score: 15, label: "Excellent", description: "Excellent multimedia integration" },
          { score: 11, label: "Good", description: "Good use of multimedia" },
          { score: 8, label: "Adequate", description: "Some multimedia" },
          { score: 4, label: "Weak", description: "Minimal multimedia" },
          { score: 0, label: "Missing", description: "Text only" },
        ],
      },
      { key: "engagement", label: "Audience Engagement", description: "Does it engage digital audiences?", maxPoints: 15,
        levels: [
          { score: 15, label: "Excellent", description: "Highly engaging" },
          { score: 11, label: "Good", description: "Engaging" },
          { score: 8, label: "Adequate", description: "Somewhat engaging" },
          { score: 4, label: "Weak", description: "Not engaging" },
          { score: 0, label: "Missing", description: "Boring" },
        ],
      },
      { key: "structure", label: "Structure & Navigation", description: "Is it well-structured for scanning/scrolling?", maxPoints: 15,
        levels: [
          { score: 15, label: "Excellent", description: "Perfect scannable structure" },
          { score: 11, label: "Good", description: "Good structure" },
          { score: 8, label: "Adequate", description: "Basic structure" },
          { score: 4, label: "Weak", description: "Poor structure" },
          { score: 0, label: "Missing", description: "No structure" },
        ],
      },
      { key: "ethics", label: "Ethics & Source Transparency", description: "Ethical digital journalism practices?", maxPoints: 10,
        levels: [
          { score: 10, label: "Excellent", description: "Exemplary ethics" },
          { score: 7, label: "Good", description: "Good ethics" },
          { score: 5, label: "Adequate", description: "Basic awareness" },
          { score: 3, label: "Weak", description: "Some concerns" },
          { score: 0, label: "Missing", description: "Ethical issues" },
        ],
      },
      { key: "revision", label: "Revision", description: "Response to feedback", maxPoints: 10,
        levels: [
          { score: 10, label: "Excellent", description: "Thoughtful revision" },
          { score: 7, label: "Good", description: "Good effort" },
          { score: 5, label: "Adequate", description: "Some revision" },
          { score: 3, label: "Weak", description: "Minimal" },
          { score: 0, label: "Missing", description: "None" },
        ],
      },
    ],
  },

  // Editing rubric
  editing_rubric: {
    id: "editing_rubric",
    name: "Editing Exercise Rubric",
    totalPoints: 100,
    categories: [
      { key: "structural_edit", label: "Structural Editing", description: "Did the student identify and address structural issues?", maxPoints: 25,
        levels: [
          { score: 25, label: "Excellent", description: "Comprehensive structural analysis and fixes" },
          { score: 19, label: "Good", description: "Good structural edits" },
          { score: 13, label: "Adequate", description: "Some structural edits" },
          { score: 6, label: "Weak", description: "Missed structural issues" },
          { score: 0, label: "Missing", description: "No structural editing" },
        ],
      },
      { key: "line_edit", label: "Line Editing", description: "Quality of line-by-line editing", maxPoints: 25,
        levels: [
          { score: 25, label: "Excellent", description: "Thorough, precise line edits" },
          { score: 19, label: "Good", description: "Good line editing" },
          { score: 13, label: "Adequate", description: "Some line edits" },
          { score: 6, label: "Weak", description: "Superficial editing" },
          { score: 0, label: "Missing", description: "No line editing" },
        ],
      },
      { key: "edit_memo", label: "Edit Memo Quality", description: "Is the edit memo clear, constructive, and professional?", maxPoints: 25,
        levels: [
          { score: 25, label: "Excellent", description: "Professional, constructive, detailed memo" },
          { score: 19, label: "Good", description: "Clear, useful memo" },
          { score: 13, label: "Adequate", description: "Basic memo" },
          { score: 6, label: "Weak", description: "Vague memo" },
          { score: 0, label: "Missing", description: "No memo" },
        ],
      },
      { key: "factual_queries", label: "Factual Queries & Verification", description: "Did the editor identify factual issues?", maxPoints: 15,
        levels: [
          { score: 15, label: "Excellent", description: "Sharp factual queries" },
          { score: 11, label: "Good", description: "Good queries" },
          { score: 8, label: "Adequate", description: "Some queries" },
          { score: 4, label: "Weak", description: "Missed issues" },
          { score: 0, label: "Missing", description: "No queries" },
        ],
      },
      { key: "reflection", label: "Reflection", description: "Reflection on the editing process", maxPoints: 10,
        levels: [
          { score: 10, label: "Excellent", description: "Insightful reflection" },
          { score: 7, label: "Good", description: "Good reflection" },
          { score: 5, label: "Adequate", description: "Basic" },
          { score: 3, label: "Weak", description: "Minimal" },
          { score: 0, label: "Missing", description: "None" },
        ],
      },
    ],
  },

  // Visual / Layout rubric
  visual_rubric: {
    id: "visual_rubric",
    name: "Layout / Visual Assignment Rubric",
    totalPoints: 100,
    categories: [
      { key: "visual_hierarchy", label: "Visual Hierarchy", description: "Is the layout well-organised with clear hierarchy?", maxPoints: 25,
        levels: [
          { score: 25, label: "Excellent", description: "Professional visual hierarchy" },
          { score: 19, label: "Good", description: "Good hierarchy" },
          { score: 13, label: "Adequate", description: "Basic hierarchy" },
          { score: 6, label: "Weak", description: "Confusing layout" },
          { score: 0, label: "Missing", description: "No hierarchy" },
        ],
      },
      { key: "display_copy", label: "Headlines, Captions & Display Copy", description: "Quality of headlines, captions, and pull quotes", maxPoints: 25,
        levels: [
          { score: 25, label: "Excellent", description: "Sharp, accurate, engaging display copy" },
          { score: 19, label: "Good", description: "Good display copy" },
          { score: 13, label: "Adequate", description: "Basic display copy" },
          { score: 6, label: "Weak", description: "Weak display copy" },
          { score: 0, label: "Missing", description: "No display copy" },
        ],
      },
      { key: "design_rationale", label: "Design Rationale", description: "Can the student explain and justify design choices?", maxPoints: 25,
        levels: [
          { score: 25, label: "Excellent", description: "Sophisticated design reasoning" },
          { score: 19, label: "Good", description: "Good rationale" },
          { score: 13, label: "Adequate", description: "Basic rationale" },
          { score: 6, label: "Weak", description: "Vague rationale" },
          { score: 0, label: "Missing", description: "No rationale" },
        ],
      },
      { key: "typography_readability", label: "Typography & Readability", description: "Is the typography appropriate and readable?", maxPoints: 15,
        levels: [
          { score: 15, label: "Excellent", description: "Professional typography" },
          { score: 11, label: "Good", description: "Good typography" },
          { score: 8, label: "Adequate", description: "Readable" },
          { score: 4, label: "Weak", description: "Hard to read" },
          { score: 0, label: "Missing", description: "Unreadable" },
        ],
      },
      { key: "reflection", label: "Reflection", description: "Reflection on visual storytelling", maxPoints: 10,
        levels: [
          { score: 10, label: "Excellent", description: "Insightful" },
          { score: 7, label: "Good", description: "Good" },
          { score: 5, label: "Adequate", description: "Basic" },
          { score: 3, label: "Weak", description: "Minimal" },
          { score: 0, label: "Missing", description: "None" },
        ],
      },
    ],
  },

  // ═══════════════════════════════════════════════════════
  // Mass Media / Writing for Mass Media Rubric (HCC109)
  // ═══════════════════════════════════════════════════════
  mass_media_rubric: {
    id: "mass_media_rubric",
    name: "Writing for Mass Media Rubric",
    totalPoints: 100,
    categories: [
      { key: "structure", label: "Structure & Format", description: "Is the correct format used for the media type? Is the structure clear and appropriate?", maxPoints: 20,
        levels: [
          { score: 20, label: "Excellent", description: "Perfect format for the media type, clear structure" },
          { score: 15, label: "Good", description: "Good format, minor issues" },
          { score: 10, label: "Adequate", description: "Basic structure present but has problems" },
          { score: 5, label: "Weak", description: "Wrong format or very poor structure" },
          { score: 0, label: "Missing", description: "No recognisable structure" },
        ],
      },
      { key: "clarity", label: "Clarity & Readability", description: "Is the writing clear, concise, and easy to understand?", maxPoints: 20,
        levels: [
          { score: 20, label: "Excellent", description: "Crystal clear, polished, professional" },
          { score: 15, label: "Good", description: "Clear and readable, minor issues" },
          { score: 10, label: "Adequate", description: "Understandable but needs editing" },
          { score: 5, label: "Weak", description: "Confusing or unclear" },
          { score: 0, label: "Missing", description: "Unreadable" },
        ],
      },
      { key: "audience_fit", label: "Audience Awareness", description: "Is the writing tailored to the target audience and medium?", maxPoints: 20,
        levels: [
          { score: 20, label: "Excellent", description: "Perfectly targeted for the medium and audience" },
          { score: 15, label: "Good", description: "Good audience awareness" },
          { score: 10, label: "Adequate", description: "Some awareness of audience" },
          { score: 5, label: "Weak", description: "Generic, no audience targeting" },
          { score: 0, label: "Missing", description: "No audience awareness" },
        ],
      },
      { key: "correctness", label: "Accuracy & Attribution", description: "Are facts accurate? Are sources properly attributed?", maxPoints: 20,
        levels: [
          { score: 20, label: "Excellent", description: "All facts verified, proper attribution throughout" },
          { score: 15, label: "Good", description: "Mostly accurate, minor attribution gaps" },
          { score: 10, label: "Adequate", description: "Some accuracy or attribution issues" },
          { score: 5, label: "Weak", description: "Significant accuracy problems" },
          { score: 0, label: "Missing", description: "Inaccurate or no attribution" },
        ],
      },
      { key: "editing_quality", label: "Editing Quality & Revision", description: "How well was the piece edited? Did the student respond to feedback?", maxPoints: 10,
        levels: [
          { score: 10, label: "Excellent", description: "Thorough editing, thoughtful revision" },
          { score: 7, label: "Good", description: "Good editing effort" },
          { score: 5, label: "Adequate", description: "Some editing done" },
          { score: 3, label: "Weak", description: "Minimal editing" },
          { score: 0, label: "Missing", description: "No editing or revision" },
        ],
      },
      { key: "reflection", label: "Reflection", description: "Quality of critical reflection on writing choices", maxPoints: 10,
        levels: [
          { score: 10, label: "Excellent", description: "Thoughtful, specific reflection" },
          { score: 7, label: "Good", description: "Solid reflection" },
          { score: 5, label: "Adequate", description: "Surface-level" },
          { score: 3, label: "Weak", description: "Minimal" },
          { score: 0, label: "Missing", description: "None" },
        ],
      },
    ],
  },
}

export function getRubricPreset(id) {
  return rubricPresets[id] || null
}

export const rubricPresetIds = Object.keys(rubricPresets)
